name: "financials"
version: "1.0.0"
config-version: 2

profile: "financials_snowflake"

model-paths: ["models"]
seed-paths: ["data"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  financials:
    staging:
      +materialized: view
    core:
      +materialized: table

seeds:
  financials:
    +header: true
    +quote_columns: false


